### ISSUE TITLE
on shop site and konfigurator

### ISSUE THREAD

**Issue by Forket** [Forket/pogea-racing.com#12]
on shop site and konfigurator : its everything to big? smaller and more compact ..to mmuch line heights

**Comment by Forket** [comment]
What does it mean - too big? can't understand what needs to be changed

**Comment by netodo** [comment]
smaller font size .smaller line height..be more compact

**Comment by Forket** [comment]
1. Changed font-size from 14px to 12px.
2. Line height left, because it's normal. is will make less than lines will overlap each other.
3. be more compact - don't understand :)

**Comment by netodo** [comment]
same issue opened already?

**Comment by Forket** [comment]
No. It's fixed :)

**Comment by netodo** [comment]
jea nice..could you make it transparent like right big block? background

**Comment by netodo** [comment]
http://new.pogea-racing.com/site15/shop/?product_cat=chiptuning

merkezttel button:
in red ... white font... like on detail page button

price: 
ul.products .price .amount {
    color: red;
    font-size: 13px;
    font-weight: bold;
    position: absolute;
    right: 0;
    top: 3px;
}

then:
.woocommerce ul.products li.product, .woocommerce-page ul.products li.product
make margin= 0 3.8% 0.5em 0

then:
.woocommerce ul.products li.product .button {
    margin-top: 0;
}

**Comment by Forket** [comment]
>merkezttel button:
>in red ... white font... like on detail page button

Done

**Comment by Forket** [comment]
>price: 
>ul.products .price .amount {
>color: red;
>font-size: 13px;
>font-weight: bold;
>position: absolute;
>right: 0;
>top: 3px;
>}

Done

**Comment by Forket** [comment]
>.woocommerce ul.products li.product, .woocommerce-page ul.products li.product
>make margin= 0 3.8% 0.5em 0

Done

**Comment by Forket** [comment]
>.woocommerce ul.products li.product .button {
>margin-top: 0;
>}

Done

**Comment by Forket** [comment]
Approve and close if OK
