### ISSUE TITLE
News Design not correct perfect

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#15]
- No Buttons on right side please 
- orientate on www.adv1wheels.com/blog: -> Should be look like this
- Please look at Font size and look that design is "elementary" the same (on my page it was ok. now client is not so happy)

**Comment by Forket** [comment]
Fixed

**Comment by netodo** [comment]
add left small block (like the right small block on adv1wheels.com/blog) and show categories as links like on adv1wheels... site ....and not on right side as buttons

**Comment by Forket** [comment]
Done.
Please approve and close issue if it's OK
