### ISSUE TITLE
Right Buttons Menu

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#16]
The right menu Buttons was on my page different length. now not anymore. Please make it like it was before. 
Different widths. Right alignment. 
now we have on new page center text align and blocks...

**Comment by Forket** [comment]
Fixed

**Comment by netodo** [comment]
if active : http://new.pogea-racing.com/site15/wer-wir-sind/partner/
please make only menu point in red...not border or what it is
see skype screeenshot...look at my page ...how active menu point should look

**Comment by Forket** [comment]
done. check. if OK - close issue
