### ISSUE TITLE
Headers Design not correct

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#17]
- please dont show page title as header 

forexample:
- http://new.pogea-racing.com/site15/wer-wir-sind/jobs-und-karriere/
- http://pogea-racing.netodo.de/?page_id=135

like on my page...do not show "JOBS UND KARRIERE"
only the header from editor field. 

- The Headers where CAPS before, everything "block capitals". and it was with very small spaces between letters of word. 
- NOt in 2 lines ...only one line header (full width)

**Comment by Forket** [comment]
Alex, page and all other titles should be controlled via CSS.
For example, there is no problem to write page title like "Jobs & Karriere: Ihr Einstieg bei POGEA RACING" in title field in page editor.
Example. 
Insteed of this 

![snapshot n001_2015-11-04_20-55-57](https://cloud.githubusercontent.com/assets/6735288/10950110/80c655c2-8336-11e5-891d-4dc5cd763b2b.png)

You should write like this:
![snapshot n001_2015-11-04_20-56-56](https://cloud.githubusercontent.com/assets/6735288/10950131/9d98e4f8-8336-11e5-9eb8-e3d43e3f2cf3.png)

**Comment by netodo** [comment]
Yes i could write it like this: BUT... this page title will be shown on right menu page and it looks not good if there is a long title name

**Comment by Forket** [comment]
Alex, it's for sure easy to do, but again. Are U sure? because of one or two pages - remove title for all pages? It would be more correct just to make not so long title. For example in above just make page title "Jobs are carriera" and in content at the start just put all other..

**Comment by netodo** [comment]
yes i am sure. cause i think client wants another title then the button ...  buut let us leave this for first... and then if he says "hey why is not like i wanted" ....we will do it..ok?

**Comment by Forket** [comment]
Agreed. leave as is and closing.
