### ISSUE TITLE
Top Menu not correct 

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#18]
Top Menu (Wer wir sind, was wir tun, news, kontakt, shop) is not 100% correct
a) wer wir sind & was wir tun should be only shown if we click on startpage on unternehmen
b) Kontakt will be deleted on top menu 
c) Make new footer menu: Products and Chiptuning Red Buttons from startpage (top). 
Could we show them also on a footer Menu? 
d) new Footer menu right of Adress in footer (grey area on bottom)
CHIPTUNING ( link same like on startpage)
PRODUCTS ( link same like on startpage)
KONTAKT (link to contact page)

**Comment by Forket** [comment]
d) - done

**Comment by Forket** [comment]
> c) Make new footer menu: Products and Chiptuning Red Buttons from startpage (top). 
> Could we show them also on a footer Menu? 
Dont' understand what U mean

**Comment by Forket** [comment]
b) - done

**Comment by Forket** [comment]
> a) wer wir sind & was wir tun should be only shown if we click on startpage on unternehmen

don't understand. I have to delete these items?

**Comment by netodo** [comment]
a) no not delete...show these 2 menu points on top menu ..if we have clicked on Unternehmen on startpage...
for example:
click on starpage on Unternehmen
Menu points on top are: 
wer wir sind, was wir tun, news, shop, kontakt

click on startpage on another link for example multimedia
show only news, shop , kontakt
do NOT show wer wir sind and was wir tun

and dont forget...:
if we clicked on wer wir sind or was wir tun...or a subpage of these 2 main menu points..then show waswir tun and wer wir sind..but on ALL other pages do not show these 2 menu points

**Comment by Forket** [comment]
Alex, it's not possible in current infrastructure because it needs analysis of current page and this pages are dynamic.

**Comment by Forket** [comment]
Closed based on mutual agreement.
