### ISSUE TITLE
Chiptuning List View

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#19]
It takes to much space ...
it should be everything smaller and narrower like on old shop page of client.

**Comment by Forket** [comment]
Old shop have different design. IN this case I need more specific details from U about what shoud I do. smaller font-size, line height etc..

**Comment by netodo** [comment]
more together...smaller spaces between the articles

**Comment by Forket** [comment]
Decreased margin bottom from 2.992em to 0.992

**Comment by netodo** [comment]
its same ticket like : https://github.com/Forket/pogea-racing.com/issues/12
