### ISSUE TITLE
Chiptuning Products Detail View like on BR Performance page

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#20]
Chiptuning Products Detail View like on BR Performance page like we have dealed it

**Comment by netodo** [comment]
http://www.br-performance.lu/de-lu/chiptuning/1-fahrzeuge/35-maserati/1572-4200-gt-coupe/1573-2003-2007/1574-4-2-v8/

**Comment by Forket** [comment]
> because of the ECO Stage1 Stage2 links...

Alex, this link relation ship is out of scope. Please, remember, that product details page design will includes information and limited only with BOXES (and info in it)

**Comment by netodo** [comment]
![product_det](https://cloud.githubusercontent.com/assets/15340006/10993450/311024e2-846f-11e5-8655-b6b43b574d1e.png)

Screendesign :) 

relations will talk later ..after finishing it

**Comment by Forket** [comment]
done. please approve

**Comment by netodo** [comment]
- Table looks to big... maybe he wants not so big padding and font size: try with: font-size: 13px on .stage-data th, .stage-data td
and try padding: 2px 15px 2px 2px 
same for .stage-data th, .stage-data td
and min height of table = 300px

- similar products should be correct -> abartht shows similar products = hyundai? no sense

- show beschreibung(description) on left and graphics on right (change these 2)

- OUR Quality should be for every product different (just make new custom field) ^^ sorry i thought its a global text but he wants for very product

- Rename "Ähnliche Produkte" to "VERWANDTE PRODUKTE" 

- Button "In den Warenkorb" rename to "MERKZETTEL"

- Articlenumber is not correct => teilenummer is not correct imported? (issue with teilenummer)

**Comment by Forket** [comment]
>Table looks to big... maybe he wants not so big padding and font size: try with: font-size: 13px on >.stage-data th, .stage-data td
>and try padding: 2px 15px 2px 2px 
>same for .stage-data th, .stage-data td
>and min height of table = 300px

Done

**Comment by Forket** [comment]
> similar products should be correct -> abartht shows similar products = hyundai? no sense

It's default login in WC. I can remove related products at all if you will comfirm

**Comment by Forket** [comment]
> show beschreibung(description) on left and graphics on right (change these 2)

Done

**Comment by Forket** [comment]
>OUR Quality should be for every product different (just make new custom field) ^^ sorry i thought its a global text but he wants for very product

added CF "Our quality". 
Done

**Comment by Forket** [comment]
> Rename "Ähnliche Produkte" to "VERWANDTE PRODUKTE"
It's in WPML string translation

**Comment by Forket** [comment]
>Button "In den Warenkorb" rename to "MERKZETTEL"

WPML string translation. But i've translated

**Comment by Forket** [comment]
>Articlenumber is not correct => teilenummer is not correct imported? (issue with teilenummer)

1. Articlenumber and TEIL number - are not the same things. Articlenumber(SKU) - generated by WC for managing products. and TEIL number -  attribute from import

**Comment by netodo** [comment]
our quality should be under "beschreibung"
font size of "bewertungen" smaller .. its to big.. make it like other boxes content

on top change kategorie and artikelnr order
kategorie first... red pogea color.
then artikelnummer (should show teilenummer)..in silver or white

will "our quality" be a custom field like videos?

**Comment by Forket** [comment]
> our quality should be under "beschreibung"

Done

**Comment by Forket** [comment]
> font size of "bewertungen" smaller .. its to big.. make it like other boxes content

Done

**Comment by Forket** [comment]
>on top change kategorie and artikelnr order
>kategorie first... red pogea color.

Done

**Comment by Forket** [comment]
>then artikelnummer (should show teilenummer)..in silver or white
Done

**Comment by Forket** [comment]
>will "our quality" be a custom field like videos?
Yes. CF name = "Our quality"

**Comment by netodo** [comment]
will let it check from client

**Comment by netodo** [comment]
bottom is not korrekt (ähnliche artikel)

**Comment by Forket** [comment]
Whats wrong? as I can see everything is OK
