### ISSUE TITLE
Teilenummer not correct (import export)

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#22]
What is with "Teilenummer" it is not correct ?
For Example Audi TT 3.2 (troyanflasher) has not correct Teilenummer and is not shown in frontend? 

http://new.pogea-racing.com/site15/shop/audi-tt-3-2-8j-vr6-250-ps-troyanflasher/

this is not crrect teilenummer shown in frontend and in backend:
correct teile nummer is: POG.TROY.003
look here: http://shop.pogea-racing.com/pogea/configurator/view
-> audi-tt-3-2-8j-vr6-250-ps-troyanflasher

not correct exported? imported?

**Comment by Forket** [comment]
Have to reimport chiptuning. Will do it today in the evening

**Comment by Forket** [comment]
Fixed. Approve and close issue if OK
