### ISSUE TITLE
mobile sites optimization

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#23]
check mobile if everything looks correctly..just check a few content sites...then shop site...list view...products...chiptuning... then detail view of article...and special sites like news etc.
should look normal. i think you know how i mean...

**Comment by Forket** [comment]
Done. Please check.

**Comment by netodo** [comment]
looks nice...if i open multimedia...
it shows the transparent menu overlapping the half screen on phone^^ 
what can we do here?

**Comment by Forket** [comment]
>..if i open multimedia...
it shows the transparent menu overlapping the half screen on phone^^ 
what can we do here?

Done

**Comment by netodo** [comment]
.widget-area from 17% to 30% please :) then it looks good

**Comment by netodo** [comment]
i will check other sites...

**Comment by netodo** [comment]
for me it looks good. will let it check from client .
News page is not perfect but here we need first more texts from client :)

**Comment by Forket** [comment]
![c13e1a475560978880cb26c51f2c2319e94200a141eeca51ba pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6735288/11338738/15819be0-91f6-11e5-95b2-be70fc51af46.jpg)
![187cc0a44588dbfa868fc0554e8849b506ff778862104fea85 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6735288/11338737/158007b2-91f6-11e5-8809-2f166f60125e.jpg)

**Comment by Forket** [comment]
Fixed

**Comment by netodo** [comment]
could you change (only on mobile) the order? 
first the selectboxes dropdown filter and then under this the result? :) is it possible?

**Comment by netodo** [comment]
2 TODOs  on mobile

Look Detail Page : http://new.pogea-racing.com/site15/shop/mercedes-benz-e-klasse-500-408-ps-stage-1/
here are the boxes not on 100% width ...its cutted after 60% ..
please make 100% width of each box (and other things too)
---------
please  show on mobile page first the select boxes filter and then the result of product and chiptuning page
--------
on http://new.pogea-racing.com/site15/was-wir-tun/chiptuning/ 
menu right .. open it...
here is showing only menu points until "öko tuning" 
but after this (look desktop) there are 3 more menu points..
---------
on galerie page
choose the last category
you see menu is on top...its to much on top...please morgen margin-top: (beginn under grey breadcrumb are)

**Comment by Forket** [comment]
1st todo - done

**Comment by Forket** [comment]
2nd todo - done

**Comment by netodo** [comment]
[19:51:12] Aleksandar Todorovic: 2 things left on mobile
[19:51:15] Aleksandar Todorovic: right menu problem
[19:51:22] Aleksandar Todorovic: and on products / chiptuning
[19:51:32] Aleksandar Todorovic: please make select boxes before results

**Comment by Forket** [comment]
>and on products / chiptuning
[19:51:32] Aleksandar Todorovic: please make select boxes before results

Done

**Comment by Forket** [comment]
>right menu problem 

Done
