### ISSUE TITLE
news design

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#24]
- add "...." at the end of description on news list
like on http://www.adv1wheels.com/blog/ 
tipp: http://blog.mixable.de/css-abschneiden-zu-langer-texte/

- everything thinner a little bit (now its to much width) (ask me)
- make sidebar on right side (not left^^)
- search button with text on top (like on http://www.adv1wheels.com/blog/ ) (ask me)
- a new background around content block and sidebar (ask me)
- add footer like on http://www.adv1wheels.com/blog/ 
-> twitter news etc too , but here talk first with me! (ask me)
- please look that detail page of news look correctly..for now it shows the sidebar not correct for example

**Comment by Forket** [comment]
>add "...." at the end of description on news list
like on http://www.adv1wheels.com/blog/ 
tipp: http://blog.mixable.de/css-abschneiden-zu-langer-texte/

Done

**Comment by Forket** [comment]
>make sidebar on right side (not left^^)

Done

**Comment by Forket** [comment]
>please look that detail page of news look correctly..for now it shows the sidebar not correct for example

Now OK

**Comment by Forket** [comment]
Clarify some points with client and provide feedback :)

**Comment by netodo** [comment]
- make a background behind the 2 boxes (content + sidebar) ..in black...like on http://www.adv1wheels.com/blog/ 
for example: .wrapper{background:red}
now you see a background behind the 2 blocks :)

- we forgot the footer on bottom  like on http://www.adv1wheels.com/blog/ 
just make a block under the (new black background) .wrapper div and set only 4 exxample <h2> texts---like on adv
recent posts | categories | twitter | recent comments
we will think about what should be here ..just prepare here 4 areas for content/widgets

- detail page not correct looking

- can i add search button on sidebar ? or can i add widgets in sidebar? is there a placeholder?

**Comment by Forket** [comment]
>can i add search button on sidebar ? or can i add widgets in sidebar? is there a placeholder?

Yes. you can. via admin side in widgets area

**Comment by Forket** [comment]
>make a background behind the 2 boxes (content + sidebar) ..in black...like on

Done

**Comment by Forket** [comment]
>we forgot the footer on bottom like on http://www.adv1wheels.com/blog/ 
just make a block under the (new black background) .wrapper div and set only 4 exxample <h2 texts---like on adv footer 
recent posts | categories | twitter | recent comments
we will think about what should be here ..just prepare here 4 areas for content/widgets

It's not correct approach. This needs to create sidebar. This is CR. Will create separate issue for this

**Comment by Forket** [comment]
>detail page not correct looking

whats wrong?

**Comment by netodo** [comment]
ok looks good again
