### ISSUE TITLE
Product Page Products Grids

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#26]
The Grids are not looking very good

http://new.pogea-racing.com/site15/shop/?product_cat=produkte

- 4 in a row
- same height! 
--> no product should be longer than another 
- same width
- same structure on every product in grids
- price should be on every product on same place 
- info should be on every product on same place 
- if for example a information or price is missing (let it empty but the row should exist (empty row)

**Comment by Forket** [comment]
>4 in a row

Done

**Comment by Forket** [comment]
> same height! --> no product should be longer than another

Done

**Comment by Forket** [comment]
> same width

Done

**Comment by Forket** [comment]
>same structure on every product in grids
price should be on every product on same place
info should be on every product on same place
if for example a information or price is missing (let it empty but the row should exist (empty row)

Done

**Comment by Forket** [comment]
Approve and Close if OK

**Comment by netodo** [comment]
detailpage is not correct on bottom :)

**Comment by Forket** [comment]
Related products made 4 items in row
