### ISSUE TITLE
Menu changes position (make this last)

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#27]
The Menu on pages for example 
1. Wer wir sind, Was wir tun, News, Gallery, Shop 
--> should not be anymore on top  (remove/delete that menu on top)

2. you see on startpage menu (transparent on bottom)
Multimedia, News, Unternehmen, 10 reasons why etc.
--> can we show this menu on EVERY PAGE and on same position! Bottom and transparent

cause the users are confused about menu^^

it was my fault cause i interpreted wrong the menu logic of him...but if we make this and he wants again changes...then we will make him change request if its ok for you :)

**Comment by Forket** [comment]
Can we do it after going live?

**Comment by netodo** [comment]
i think this is go live relevant^^

**Comment by Forket** [comment]
Done. Approve and close issue if OK
