### ISSUE TITLE
issues 

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#31]
always look at screens: i dont know which screen is which todo^^

1. Menu bottom 
should be on top of footer. just position it a little bit more bottom :) cause they can not click on products on botttom in dropdown (for example toyota like on screen) ^^

2. as i said: show the dropdowns of shop on detail page please  (we forgot to do it again^^) 	cause when client is selecting dropdowns and then choosing a produkt and on detail page he can not go back 
if he click on browser: back ...then he has to choose dropdown new :( (can we do it with session maybe?)
for example on pogea-racing.com you can see on shop site the dropdown is always there with selected cars and options

3.News
can we show right sidebar block until footer? as long as the content?

3.1 can we make same width on shop site like on news site? content on shop site = same width like on news , sidebar of shopsite = same width of news sideba
(llooook screens)
forexample: news content width is for exampple 2400px then make shop content to (but only these 2) and the same on sidebar

4. starpage 
(look at screen with startpage)
should loook like this

5. buttons or on request look at screen with on reqeust list on shop site...i dont know whats happened^^ (if you choose another order...f.ex..order by price -> http://new.pogea-racing.com/site15/shop/?orderby=price&product_cat=chiptuning
just disable button...and make "on request" on top of line like the price

link to products on startpage dont works

have to wait till client makes more images on anleitungen....cause i think design is not correct?

i think on opera is only one problem on startpage (look buttons white background)

screens are on link i send you

**Comment by Forket** [comment]
> Menu bottom 
should be on top of footer. just position it a little bit more bottom :) cause they can not click on products on botttom in dropdown (for example toyota like on screen) ^^

Done

**Comment by Forket** [comment]
>as i said: show the dropdowns of shop on detail page please (we forgot to do it again^^) cause when client is selecting dropdowns and then choosing a produkt and on detail page he can not go back 
if he click on browser: back ...then he has to choose dropdown new :( (can we do it with session maybe?)
for example on pogea-racing.com you can see on shop site the dropdown is always there with selected cars and options

Done

**Comment by Forket** [comment]
>link to products on startpage dont works

Works
http://new.pogea-racing.com/site15/shop/?product_cat=produkte

**Comment by Forket** [comment]
> 2.as i said: show the dropdowns of shop on detail page please (we forgot to do it again^^) cause when client is selecting dropdowns and then choosing a produkt and on detail page he can not go back 
if he click on browser: back ...then he has to choose dropdown new :( (can we do it with session maybe?)
for example on pogea-racing.com you can see on shop site the dropdown is always there with selected cars and options

Done

**Comment by Forket** [comment]
>3.News
can we show right sidebar block until footer? as long as the content?

Done

**Comment by Forket** [comment]
Please review and approve if OK. If not - open new issue for every new bug.
Some of things are CRs

**Comment by netodo** [comment]
-i think on opera is only one problem on startpage (look buttons white background) 
and on IE also i think
- can we move the shop_sidebar_1 "sidebar on shop select boxes" into the transparent box like on news? :) i tried it but it dont want to move right of content box :(

**Comment by Forket** [comment]
> i think on opera is only one problem on startpage (look buttons white background) and on IE also i think... but not sure...i remembered something is went wrong on other browser...firefox and chrome is good looking

Here is screen from Opera. Where is the problem?
![snapshot n001_2015-11-23_12-27-22](https://cloud.githubusercontent.com/assets/6735288/11335573/9a1ce3b4-91dd-11e5-9af0-e4c5a7babba8.png)

**Comment by Forket** [comment]
>can we move the shop_sidebar_1 "sidebar on shop select boxes" into the transparent box like on news? :) i tried it but it dont want to move right of content box :( -> http://new.pogea-racing.com/site15/shop/?car_type=1-4tjet-euro-6-135ps&product_cat=chiptuning

Done

**Comment by netodo** [comment]
.widget-area from 17% to 30% please :) then it looks good

**Comment by Forket** [comment]
> .widget-area from 17% to 30% please :) then it looks good

Done
