### ISSUE TITLE
order of article chiptuning boxes

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#33]
order of products boxes

Beschreibung = 1st
Performance = 2nd
Qualität = 3rd
video = 4th
Gallery = 5th
Rezension / Bewertungen = LAST

**Comment by Forket** [comment]
Can U give me some product where all boxes are present?

**Comment by netodo** [comment]
http://new.pogea-racing.com/site15/shop/mercedes-benz-e-klasse-500-408-ps-stage-1/

**Comment by netodo** [comment]
http://new.pogea-racing.com/site15/shop/mercedes-benz-e-klasse-500-408-ps-stage-1/

**Comment by Forket** [comment]
Done
