### ISSUE TITLE
"unser team" dont break word 

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#37]
http://new.pogea-racing.com/site15/wer-wir-sind/ueber-uns/

you can see here.
for example

martin maciejok 
is cutted 0f
martin macie- 
jok

cant we show it like this? : :
Martin 
Maciejok

on next line if doesnt fit?

**Comment by Forket** [comment]
But it's OK. Where U can see cutting?

![snapshot n001_2015-12-03_19-17-18](https://cloud.githubusercontent.com/assets/6735288/11569490/7917128a-99f2-11e5-9b48-9c487d0e4ee5.png)

**Comment by netodo** [comment]
![test123](https://cloud.githubusercontent.com/assets/15340006/11569534/bffc99b8-99f2-11e5-95de-2e3cb8aba4aa.png)

**Comment by Forket** [comment]
It's in firefox only

**Comment by Forket** [comment]
Check
