### ISSUE TITLE
gallery content

### ISSUE THREAD

**Issue by netodo** [Forket/pogea-racing.com#42]
I dont know how to configure it...
could you please show only the first main categories on this site please:
http://new.pogea-racing.com/site15/gallery/

for example:
http://new.pogea-racing.com/site15/wp-admin/edit-tags.php?taxonomy=gallery_category&post_type=attachment
look at backend at categories
- should be shown: 
DYNO Gallery
Hall of Fame
The Centurion 4C

Ausstellungen not because it has no images in it and no sub categories with images...

PS: i have now added function...to show sub categories of active category

**Comment by Forket** [comment]
Fixed.
