### ISSUE TITLE
position of top menu on was wir tun is not good positioned

### ISSUE THREAD

**Issue by Forket** [Forket/pogea-racing.com#6]
position of top menu on was wir tun is not good positioned (talktome)

**Comment by Forket** [comment]
Please, explain.

**Comment by netodo** [comment]
http://new.pogea-racing.com/site15/was-wir-tun/tuev-sondereintragungen/

please make top menu more right ...kontakt should end like end of black content box under it ...on same line

**Comment by Forket** [comment]
it's not possible because:
1. header and content are from different blocks.
2. header has 3 inline blocks (logo, menu, language) and they can only be positioned between themselves)
To make this possible I have to change a lot in design. 
is this so important that it worth this?

**Comment by netodo** [comment]
iwill check it.
