### ISSUE TITLE
header format css is wrong

### ISSUE THREAD

**Issue by Forket** [Forket/pogea-racing.com#7]
header format css is wrong..on my old site netodo... wir had it perfect he said ( i think bigger?) ..just compare
other 2 images...

**Comment by Forket** [comment]
Don't understand :)

**Comment by netodo** [comment]
on my old website the headers of each page was correct. please make it the same styling.
for example on: http://new.pogea-racing.com/site15/was-wir-tun/tuev-sondereintragungen/

the <h1>tüv sondereintragungen>

**Comment by Forket** [comment]
I'll make it red and uppercase. But U sure to make letters almost overlapping each other?
![snapshot n001_2015-10-29_11-14-15](https://cloud.githubusercontent.com/assets/6735288/10815740/44a504d8-7e2e-11e5-8cc9-4c1e5dcea531.png)

**Comment by Forket** [comment]
Done
http://new.pogea-racing.com/site15/was-wir-tun/tuev-sondereintragungen/

**Comment by netodo** [comment]
header problem already opened in another ticket?

**Comment by Forket** [comment]
No. but it's fixed
http://new.pogea-racing.com/site15/was-wir-tun/tuev-sondereintragungen/

**Comment by netodo** [comment]
font size of header h1 = 27px please

**Comment by Forket** [comment]
Done
