### ISSUE TITLE
link blog / page content

### ISSUE THREAD

**Issue by Forket** [Forket/pogea-racing.com#8]
link blog / page content: grey line area on top -> to big 50% smaller link

**Comment by Forket** [comment]
Where is blog?

**Comment by netodo** [comment]
he means breadcrumb...grey area... on every site...font size is to big... please reduce 50% and make the grey line smaller / thinner

**Comment by Forket** [comment]
Done.
![snapshot n001_2015-10-29_11-07-31](https://cloud.githubusercontent.com/assets/6735288/10815568/45f3fa34-7e2d-11e5-9a6b-2a2b642260a2.png)
